server:
  # 端口
  port: 8080
  # 访问时间
  session-timeout: 60
  # tomcat配置
  tomcat:
    max-threads: 8000
    uri-encoding: UTF-8
  # servlet的基础配置
  servlet:
    context-path: /api
spring:
  #redis配置
  #Redis服务器地址
  redis:
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #连接超时时间（毫秒）
    timeout: 5000
    password:
    #Redis数据库索引（默认为0）
    database: 0
    #连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 10000
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 2
  # 数据库链接
  datasource:
    url: jdbc:mysql://121.41.222.223:3306/business?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: broot
    password: rMBFzdJFJWYfBXfY
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
  # http的基础配置
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  # 过滤为null的数据
  jackson:
    default-property-inclusion: non_null
# 打印日志
#logging:
#  level:
#    com.mapper: trace
## mybatis-plus配置
mybatis-plus:
  # 删除主键ID
  global-config:
    db-config:
      logic-not-delete-value: "0"
      logic-delete-value: "1"
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/mapper/xml/*.xml
  # xml文件映射实体类
  typeAliasesPackage: com.entity

#域名
yuming: "https://simon.ufcoux.com"
